# Example of docker-compose script to run nginx-lego
version: '3'

services:
  nginx:
    image: nginx-lego:alpine
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - SSL_DOMAIN=${APP_SSL_DOMAIN}
      - SSL_ADMIN_EMAIL=${APP_SSL_ADMIN_EMAIL}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log
      - nginx-letsencrypt-accounts:/etc/lego/accounts
      - nginx-letsencrypt-certs:/etc/lego/certificates

volumes:
  nginx-logs:
  nginx-letsencrypt-accounts:
  nginx-letsencrypt-certs:
